---
ID: "95e8b703-0316-4e29-9051-9dcf0e20bdc0"
Parent: "57df2bfc-2440-473a-a751-18199a6e9e29"
Template: "57df2bfc-2440-473a-a751-18199a6e9e29"
Path: "/sitecore/client/Applications/FormsBuilder/Components/Layouts/Renderings/ImageSelector/FormImageSelector-Parameters/__Standard Values"
DB: core
SharedFields:
- ID: "3e079fc3-6b2d-41c9-9204-374a786fc761"
  Hint: BindingConfiguration
  Value: %7bName%7d=ImageSource
- ID: "c5217339-80d0-4725-9340-574eed8e9082"
  Hint: RenderingItemId
  Value: "{C70A35B9-4A25-416D-BFA9-4D2A85B21DC7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170725T123253Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
