---
ID: "40df18e3-5507-4968-9de6-3a205b30395c"
Parent: "67f40fef-b3c7-4366-b026-183e80dcf4e6"
Template: "67f40fef-b3c7-4366-b026-183e80dcf4e6"
Path: /sitecore/templates/Project/Eurolife/Page Types/Blog/Blog Post/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191203T124248Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191203T091911Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
