trigger: 
  branches:
    include: 
    - '*'

variables:
  gitUrl: github.com/papilias/eurolife.git
  azureUrl: https://$(username):$(azureToken)@dev.azure.com/LinakisDigitalTeam/Eurolife/_git/$(repoFolder)
  username: ipDevOps
  gitToken: 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
  azureToken: D6dVqY6yt4jcs8MqsB4rGiuBsTKPIaGAxrTG7yKd5xPlsIWXcvrqJQQJ99BBACAAAAAa2GlcAAASAZDOSs1G
  version: $(Build.BuildNumber)
  branch: $(Build.SourceBranchName)
  repoFolder: Sitecore

pool:
  vmImage: ubuntu-latest
# pool:
#   name: 'DevOps'
#   demands:
#       - agent.name -equals InternalIT-Agent

steps:
- checkout: none
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone --branch $(branch) $(azureUrl) --single-branch
      cd $(repoFolder)
      git config --global user.email "i.papadodimas@linakis.com"
      git config --global user.name "Ilias"
      git add .
      git commit -m "Push version $(version)"
      git remote set-url origin https://$(username):$(gitToken)@$(url)
      git push -u origin $(branch)