trigger: 
  branches:
    include: 
    - '*'

variables:
  url: github.com/papilias/eurolife.git
  username: ipDevOps
  variable_token: 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
  version: $(Build.BuildNumber)
  branch: $(Build.SourceBranchName)
  repoFolder: PWS_Sitecore

pool:
  vmImage: ubuntu-latest
# pool:
#   name: 'DevOps'
#   demands:
#       - agent.name -equals InternalIT-Agent

steps:
- checkout: none
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone --branch $(branch) $(url) --single-branch
      cd $(repoFolder)
      git config --global user.email "i.papadodimas@linakis.com"
      git config --global user.name "Ilias"
      git add .
      git commit -m "Push version $(version)"
      git remote set-url origin https://$(username):$(variable_token)@$(url)
      git push -u origin $(branch)