---
ID: "09bc0c12-8ba4-448a-84f3-63b63f940230"
Parent: "80ea3c96-2cca-4d69-8824-4b24e9770cbb"
Template: "80ea3c96-2cca-4d69-8824-4b24e9770cbb"
Path: /sitecore/templates/Project/Common/Content Types/PDFs Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{906A3DE5-2DD5-43EC-82E1-87D97D7C336C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190520T134213Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
