---
ID: "a538585a-f5a8-4553-8511-edde98325bff"
Parent: "a8d9a23e-92b8-4498-9fb7-c55bcfd53d8e"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Complaint Form/Page/Section/contractType/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190627T141109Z
