---
ID: "9c3e397d-93f7-479d-8511-0b135647385c"
Parent: "a8c5bbba-095f-4bb4-be7b-5c0f9ab5d52d"
Template: "a8c5bbba-095f-4bb4-be7b-5c0f9ab5d52d"
Path: /sitecore/templates/Project/Eurolife/Page Types/EurolifeCalculatorTool/CalculatorToolPage/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{373393A6-AA10-4771-B9C2-2EA1EB0583F5}">
        <r
          id="{20E8AA26-11C7-4A12-B7E3-A8F7C8200071}"
          ph="head"
          uid="{9C47714E-18C1-4A71-8D0F-C8B075136B5F}" />
        <r
          id="{9DEB13A3-A845-45C1-9AFC-3988EF0493BC}"
          ph="page-layout"
          uid="{CA703068-68F0-403C-B84F-849AD2003152}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201214T153721Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
