---
ID: "2173d991-a054-4a13-aea1-4b5a9545c1d9"
Parent: "e21cdcef-ea02-43d8-91d2-4010dc48ad2e"
Template: "e21cdcef-ea02-43d8-91d2-4010dc48ad2e"
Path: "/sitecore/client/Applications/FormsBuilder/Components/Layouts/Renderings/KeyValuePairEditor/KeyValuePairEditor-Parameters/__Standard Values"
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161027T113219Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
