---
ID: "45688414-818b-4c80-b4a3-29040f6d2c2a"
Parent: "58bcaa2a-cf40-4875-8437-3450d0e86d6f"
Template: "1f5fe211-9468-4de4-93a5-a6a9de5b1d14"
Path: /sitecore/client/Applications/FormsBuilder/Components/Layouts/FormSettingsPropertyGrid/PageSettings/FormSettingsContextDetails
DB: core
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: FormularIndstillingerKontekstDetaljer
  Versions:
  - Version: 1
    Fields:
    - ID: "242c3070-219e-4f25-ac42-d4131c4e757c"
      Hint: HeaderTitle
      Value: Formularindstillinger
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T100306Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "848f6a2b-f7fb-481b-a291-28494ad2a866"
      Hint: HeaderSubtitle
      Value: Administrer de indstillinger, der er relateret til din formular.
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: FormulareinstellungenKontextDetails
  Versions:
  - Version: 1
    Fields:
    - ID: "242c3070-219e-4f25-ac42-d4131c4e757c"
      Hint: HeaderTitle
      Value: Formular Einstellungen
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T100604Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "848f6a2b-f7fb-481b-a291-28494ad2a866"
      Hint: HeaderSubtitle
      Value: Verwalten Sie die Einstellungen, die mit Ihrem Formular zusammenhängen.
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "242c3070-219e-4f25-ac42-d4131c4e757c"
      Hint: HeaderTitle
      Value: Form settings
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161128T121711Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "848f6a2b-f7fb-481b-a291-28494ad2a866"
      Hint: HeaderSubtitle
      Value: Manage the settings related to your form.
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: フォーム設定コンテキスト詳細
  Versions:
  - Version: 1
    Fields:
    - ID: "242c3070-219e-4f25-ac42-d4131c4e757c"
      Hint: HeaderTitle
      Value: フォーム設定
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T100840Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "848f6a2b-f7fb-481b-a291-28494ad2a866"
      Hint: HeaderSubtitle
      Value: フォームに関連する設定を管理します
- Language: "zh-CN"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 表单设置上下文详情
  Versions:
  - Version: 1
    Fields:
    - ID: "242c3070-219e-4f25-ac42-d4131c4e757c"
      Hint: HeaderTitle
      Value: 表单设置
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T101122Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "848f6a2b-f7fb-481b-a291-28494ad2a866"
      Hint: HeaderSubtitle
      Value: 管理与表单相关的设置。
