---
ID: "775c186e-308c-494e-a5b2-268b43de1c9b"
Parent: "417da68a-f3a5-4f0e-b96d-8fbff6ff72e1"
Template: "417da68a-f3a5-4f0e-b96d-8fbff6ff72e1"
Path: /sitecore/templates/Project/Eurolife/Page Types/Blog/Blog Main/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191203T092030Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
