---
ID: "3a36c856-7bfe-480d-a7b7-0d384ae03fd8"
Parent: "416d9dc8-e1cc-44d7-ba57-38717f1f9a30"
Template: "416d9dc8-e1cc-44d7-ba57-38717f1f9a30"
Path: "/sitecore/client/Applications/FormsBuilder/Components/Layouts/Renderings/Composites/SubmitActionsManager/SubmitActionsManager-Parameters/__Standard Values"
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170329T125100Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
